services:
  - type: web
    name: memories-trip-app
    env: node
    buildCommand: npm install
    startCommand: node server.js
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 5
